.\" Manpage for synchronice.
.\" Contact Mohammed Ismail Ansari <team.terminal@gmail.com> to correct errors or typos.
.TH synchronice 1 "04/01/2020" "0.1.0"
.SH NAME
synchronice \- A text-based frontend for Syncthing
.SH SYNOPSIS
.B synchronice
\fISUBCOMMAND\fR
[\fIARG\fR]
.SH DESCRIPTION
.B synchronice
Starts a curses-based interface for Syncthing.
.SH SUBCOMMANDS
.TP
.BR help
Prints this message or the help of the given subcommand(s).
.TP
.BR version
Prints the version number of synchronice.
.TP
.BR restart
Restarts Syncthing.
.SH BUGS
No known bugs.
.SH AUTHOR
Mohammed Ismail Ansari (team.terminal@gmail.com)
